### ISSUE TITLE
GS checklist

### ISSUE THREAD

**Issue by z16** [z16/packages#5]
* Core
  - [x] Set parser
  - [x] Trigger logic
  - [x] Set/item validation
  - [x] Slot finagling (part 1)
  - [ ] Slot finagling (part 2
  - [x] Enrich event object (action)
  - [ ] Set/rule file templates
  - [ ] Augment selection
  - [ ] Slot locking mechanism
* Set files
  - [x] Implement file selection logic
  - [ ] Add option to include other files
  - [ ] Add mechanism to inherit from sets
  - [ ] Item lock specifier
  - [ ] Empty item specifier
  - [ ] Augment specifier
* Rule files
  - [x] Implement file selection logic
  - [x] Implement `equip`
  - [x] Implement events (pre/mid/after)
  - [x] Default rule implementations
  - [ ] Handle pet abilities
  - [ ] Handle item usage
* Command handler
  - [x] Open user folder
  - [x] Copy current equipment to clipboard
  - [x] Open UI
  - [x] Strip all gear
  - [x] Trigger `reset`
  - [ ] `new` command (see file templates)
* UI
  - [x] Implement equipment/status window
  - [x] Implemented set viewer
  - [x] Implemented set editor
  - [x] Create new files
  - [x] Manipulate sets (create, rename, remove)
  - [x] Error checking/validation
  - [x] Implement swap history
  - [x] Implement set builder
  - [x] Implement name browser
  - [ ] Make UI pretty with icons
  - [ ] View/edit included files
  - [ ] View/edit set inheritance
